### ISSUE TITLE
Text in header is small and not easily visible

### ISSUE THREAD

**Issue by jinpark** [djangogirlscodecamp/dgrsvpsite#40]
![image](https://cloud.githubusercontent.com/assets/1847812/14736452/28a00d6e-08b2-11e6-86a6-0b715b53980a.png)

Make the font bigger and probably add some kind of darkening on top of the header image

**Comment by hassanabidpk** [comment]
Did you fix it Rachell ?

**Comment by RachellCalhoun** [comment]
Let me know if this is good enough. 
![resources](https://cloud.githubusercontent.com/assets/10239547/15459474/a2d2272a-20e0-11e6-910e-f2af0d57fb15.png)

**Comment by jinpark** [comment]
👍
