### ISSUE TITLE
Send welcome people to approved users

### ISSUE THREAD

**Issue by hassanabidpk** [djangogirlscodecamp/dgrsvpsite#53]
There should be a way to send automated welcome email to users we approve from admin.

**Comment by jinpark** [comment]
good idea. 

the way I would tackle this is to create a custom task in the admin where you can approve and email at the same time. 

@sujinleeme can I get a script of what to write in the email? SOmething like, 

hello, welcome to django girls seoul. your account just got approved! Check out our current events and resources!

**Comment by hassanabidpk** [comment]
Fixed in #56 and #55
